# Generated by Django 5.0 on 2023-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_link', models.TextField()),
                ('short_link', models.CharField(max_length=10)),
            ],
        ),
    ]
